[extend]
useDefault = true

[allowlist]
description = "Chave pública e documentada do emulador Azurite (usada só nos testes de CI)"
regexes = ['''Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==''']
